import { Task } from "./types";

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Redesign landing page hero section",
    description: "Create a new hero section with updated illustrations and copy.",
    category: "design",
    status: "in-progress",
    deadline: "2026-03-25",
    submittedBy: "Sarah Chen",
    submittedAt: "2026-03-10",
    progress: 60,
  },
  {
    id: "2",
    title: "Build API endpoint for user profiles",
    description: "Implement REST endpoints for CRUD operations on user profiles.",
    category: "dev",
    status: "pending",
    deadline: "2026-03-28",
    submittedBy: "Alex Rivera",
    submittedAt: "2026-03-12",
    link: "https://github.com/example/repo",
    progress: 20,
  },
  {
    id: "3",
    title: "Competitive analysis report",
    description: "Research top 5 competitors and prepare a comparison document.",
    category: "research",
    status: "completed",
    deadline: "2026-03-15",
    submittedBy: "Maya Johnson",
    submittedAt: "2026-03-08",
    progress: 100,
  },
  {
    id: "4",
    title: "Mobile navigation prototype",
    description: "Design and prototype the mobile navigation flow in Figma.",
    category: "design",
    status: "pending",
    deadline: "2026-03-30",
    submittedBy: "James Park",
    submittedAt: "2026-03-14",
    progress: 10,
  },
  {
    id: "5",
    title: "Setup CI/CD pipeline",
    description: "Configure GitHub Actions for automated testing and deployment.",
    category: "dev",
    status: "in-progress",
    deadline: "2026-03-22",
    submittedBy: "Priya Patel",
    submittedAt: "2026-03-11",
    progress: 75,
  },
  {
    id: "6",
    title: "User interview synthesis",
    description: "Compile and analyze findings from 10 user interviews.",
    category: "research",
    status: "in-progress",
    deadline: "2026-03-20",
    submittedBy: "Tom Wilson",
    submittedAt: "2026-03-09",
    progress: 45,
  },
];
